package main;

public class Main {
    public static void main(String[] args) {
        new Game();

    }
}

/*
FIXME
    PLAY MENU BGM MUSIC ONCE COMPLETED
    ALSO RESET EVERYTHING STORY FLAGS WHEN COMPLETED
    PLAYER GOES INSIDE BLOCK
    RUNNING SOUND DOESN'T PLAY LOOP
    FIX AT THE START WHEN FALLING FOR A CERTAIN TIME IT"S NOT MOVABLE
*/
